type Shop @model {
  id: String!
  name: String!
  slug: String
  region: String
  userName: String
  category: String
  address: String
  notes: String
  ordersByPhoneOrWhatsApp: String
  delivery: String
  takeaway: String
  whatsAppNumber: String
  phoneNumber: String
  email: String
  submittedAt: String
  openTimes: String
  deliveryCost: String
  visibility: Visibility
  logo: String
  background: String
  typeformToken: String	
#  sections: [Section] @connection(keyName: "byShop", fields: ["id"])
}

enum Visibility {
  public
  private
}


#type Section @model @key(name: "byShop", fields: ["shopID"]) {
#  id: String!
#  title: String!
#  shopID: String!
#  shop: Shop @connection(fields: ["shopID"])
#  products: [Product] @connection(keyName: "bySection", fields: ["id"])
#}

#type Product @model @key(name: "bySection", fields: ["sectionID", "name"]) {
#  id: String!
#  sectionID: String!
#  section: Section @connection(fields: ["sectionID"])
#  name: String!
#  description: String
#  price: Float
#}
