type Shop @model @key(name: "bySlug", fields: ["slug"]) {
  id: ID!
  name: String!
  slug: String
  region: String
  userName: String
  category: String
  address: String
  notes: String
  ordersByPhoneOrWhatsApp: String
  delivery: String
  takeaway: String
  whatsAppNumber: String
  phoneNumber: String
  email: String
  submittedAt: String
  openTimes: String
  deliveryCost: String
  visibility: Visibility
  logo: String
  background: String
  typeformToken: String
  # products: [Product] @connection(name: "ShopProduct")
  prods: [Product] @connection(keyName: "byShop", fields: ["id"])
}

enum Visibility {
  public
  private
}

type Product @model @key(name: "byShop", fields: ["shopID", "name"]) {
  id: ID!
  shopID: ID!
  category: String!
  name: String!
  description: String
  #  price: Float
  # shop: Shop @connection(name: "ShopProduct")
}
