
type Shop @model
# @key(name: "byName", fields: ["id", "name"])
@key(name: "bySlug", fields: ["slug"]) 
{
  id: ID!
  name: String!
  slug: String!
  region: String
  userName: String
  category: String
  address: String
  notes: String
  ordersByPhoneOrWhatsApp: String
  delivery: String
  takeaway: String
  whatsAppNumber: String
  phoneNumber: String
  email: String
  submittedAt: String
  openTimes: String
  deliveryCost: String
  visibility: Visibility
  logo: String
  background: String
  typeformToken: String
  ordersPhoneNumber: String
  ordersWhatsAppNumber: String
  products: [Product] @connection(name: "ShopProducts", limit: 5000)
}

enum Visibility {
  public
  private
}

type Product @model {
  id: ID!
  category: String!
  name: String!
  description: String
  price: Float
  shop: Shop @connection(name: "ShopProducts")  # productShopId
  itemNumber: Int
}